#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-

""" main executable for instl """

import sys
# force stdout to be utf-8. Sometimes it opens in ascii encoding
sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf8', buffering=1, errors='backslashreplace')
sys.stderr = open(sys.stderr.fileno(), mode='w', encoding='utf8', buffering=1, errors='backslashreplace')


from pyinstl.instl_main import instl_own_main, InvocationReporter

if __name__ == "__main__":
    if 'run_this' in sys.argv:
        sys.argv.remove('run_this')
        with InvocationReporter(argv=sys.argv):
            instl_own_main(argv=sys.argv)
    else:
        sys.argv.append('run_this')
        command = "'" +"' '".join(sys.argv)+"'"
        from subprocess import Popen, PIPE
        scpt = f'''
                set shCmds to "{command}"
                do shell script shCmds with administrator privileges  
        '''
        p = Popen(['osascript', '-', ], stdin=PIPE, stdout=PIPE, stderr=PIPE)
        stdout, stderr = p.communicate(scpt.encode())
        return_code = p.returncode
        print(return_code)
        print(stderr)
