#!/usr/bin/env python2.7

from __future__ import print_function

import sys
import os

from pysvnsrv.svninst_interactive import go_interactive
from pysvnsrv.svninst_outeractive import go_outeractive

def main():
    try:
        if len(sys.argv) == 1:
            go_interactive()
        else:
            go_outeractive()
    except Exception as ex:
        print("unhandled exception")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()

