#!/usr/bin/env python2.7

from __future__ import print_function

#noinspection PyBroadException,PyBroadException
def main():
    #noinspection PyUnusedLocal
    try:
        if len(sys.argv) == 1:
            from pysvnsrv.svninst_interactive import go_interactive
            go_interactive()
        else:
            from pysvnsrv.svninst_outeractive import go_outeractive
            go_outeractive()
    except Exception as ex:
        print("unhandled exception")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()

