DROP TRIGGER IF EXISTS translate_require_by_trigger2;
DROP TRIGGER IF EXISTS create_require_for_installed_iids_trigger2;
DROP TRIGGER IF EXISTS remove_require_for_uninstalled_iids_trigger2;
DROP TRIGGER IF EXISTS adjust_active_os_for_details2;
DROP TRIGGER IF EXISTS set_active_os_for_details2;
DROP TRIGGER IF EXISTS add_iid_to_FoundOnDiskItemRow_guid_not_null2;
DROP TRIGGER IF EXISTS add_iid_to_FoundOnDiskItemRow_guid_is_null2;
DROP TRIGGER IF EXISTS log_adjust_active_os_for_details2;
DROP TRIGGER IF EXISTS set_adjusted_source2;
