#!/usr/bin/env python3.12
"""Core InstlClient behavior (command dispatch, default-var setup,
yaml representation) extracted verbatim from pyinstl/instlClient.py.

Pure structural decomposition: code MOVED verbatim, no logic changes.

NOTE on name mangling and defaults reading: __init__, the
all_iids_by_target_folder / no_copy_iids_by_sync_folder properties and
sort_all_items_by_target_folder all touch the private (double-underscore)
attributes, and __init__ relies on super().__thisclass__.__name__ resolving to
"InstlClient" (to read defaults/InstlClient.yaml). Those members are therefore
intentionally NOT in this mixin -- they live directly on the composed
InstlClient class in pyinstl/client/__init__.py so that name mangling resolves
to _InstlClient__... and __thisclass__ stays InstlClient, exactly as before the
split.
"""
import os
from collections import OrderedDict
import logging
log = logging.getLogger()

import utils
import aYaml
from ..instlInstanceBase import InstlInstanceBase, check_version_compatibility
from configVar import config_vars
from pybatch import *
from ..connectionBase import connection_factory


class _CoreClientMixin:

    def do_command(self):
        active_oses: List[str] = list(config_vars["TARGET_OS_NAMES"])
        # utils.add_to_actions_stack(f"""updating DB: active oses'""")
        self.items_table.activate_specific_oses(*active_oses)

        main_input_file_path: str = os.fspath(config_vars["__MAIN_INPUT_FILE__"]) #usualy the YAML file generated by central
        self.read_yaml_file(main_input_file_path, connection_obj=connection_factory(config_vars), progress_callback=self.progress)

        self.db.set_db_file_owner()

        verOK, errorMessage = check_version_compatibility()
        if not verOK:
            raise Exception(errorMessage)

        self.init_default_client_vars()

        active_oses: List[str] = list(config_vars["TARGET_OS_NAMES"])
        self.items_table.activate_specific_oses(*active_oses)

        self.items_table.resolve_inheritance()

        # is not longer active, will probably skip this phase
        if self.should_check_for_binary_versions():
            self.progress("check versions of installed binaries")
            self.get_version_of_installed_binaries()
            self.items_table.add_require_version_from_binaries()
            self.items_table.add_require_guid_from_binaries()
        self.items_table.create_default_items(iids_to_ignore=self.auxiliary_iids)
        #resolve abs path for two external tools which central holds and do not exits in the system (for instance curl for win)
        self.resolve_defined_paths()
        self.batch_accum.set_current_section('pre') #section, all commads will be inserted to section 'pre', used for switching commands order
        self.save_previous_state() #used for debug purposes, saves the old require in case of a sudden crash
        command_title = {'sync': 'download', 'uninstall': 'uninstall', 'remove': 'remove', 'read_yaml': 'yaml', "report_versions": "report"}
        self.progress(f"""calculate {command_title.get(self.fixed_command, "install")} items""")
        self.calculate_install_items()
        self.read_defines_for_active_iids()
        #self.platform_helper.num_items_for_progress_report = int(config_vars["LAST_PROGRESS"])
        #self.platform_helper.no_progress_messages = "NO_PROGRESS_MESSAGES" in config_vars

        do_command_func = getattr(self, "do_" + self.fixed_command)
        do_command_func()
        self.command_output()
        self.items_table.config_var_list_to_db(config_vars)

    def command_output(self):
        # utils.add_to_actions_stack("writing batch file..")
        self.write_batch_file(self.batch_accum)
        self.write_config_vars_to_file(config_vars.get("__WRITE_CONFIG_VARS_TO_FILE__", None).Path())
        if bool(config_vars["__RUN_BATCH__"]):
            self.run_batch_file()

    def init_default_client_vars(self):
        if "SYNC_BASE_URL" in config_vars:
            resolved_sync_base_url = config_vars["SYNC_BASE_URL"].str()
            url_main_item = utils.main_url_item(resolved_sync_base_url)
            config_vars["SYNC_BASE_URL_MAIN_ITEM"] = url_main_item
        # TARGET_OS_NAMES defaults to __CURRENT_OS_NAMES__, which is not what we want if syncing to
        # an OS which is not the current
        if config_vars["TARGET_OS"].str() != config_vars["__CURRENT_OS__"].str():
            target_os_names = list(config_vars[config_vars.resolve_str("$(TARGET_OS)_ALL_OS_NAMES")])
            config_vars["TARGET_OS_NAMES"] = target_os_names
            second_name: str = config_vars["TARGET_OS"].str()
            if len(target_os_names) > 1:
                second_name = target_os_names[1]
            config_vars["TARGET_OS_SECOND_NAME"] = second_name

        # AUXILIARY_IIDS are iids that are not real products such as UNINSTALL_AS_... iids
        if "AUXILIARY_IIDS" not in config_vars:
            log.warning(f"could not find configVar 'AUXILIARY_IIDS'")
        self.auxiliary_iids.extend(list(config_vars.get("AUXILIARY_IIDS", [])))

        config_vars["__MAIN_DRIVE_NAME__"] = utils.get_main_drive_name()

    def repr_for_yaml(self, what=None, resolve=False):
        """ Create representation of self suitable for printing as yaml.
            parameter 'what' is a list of identifiers to represent. If 'what'
            is None (the default) create representation of everything.
            InstlInstanceBase object is represented as two yaml documents:
            one for define (tagged !define), one for the index (tagged !index).
        """
        retVal = list()
        all_iids = self.items_table.get_all_iids()
        all_vars = sorted(config_vars.keys())
        if what is None:  # None is all
            what = all_vars + all_iids

        defines = OrderedDict()
        indexes = OrderedDict()
        unknowns = list()
        for identifier in what:
            if identifier in all_vars:
                defines.update({identifier: config_vars.repr_var_for_yaml(identifier)})
            elif identifier in all_iids:
                indexes.update({identifier: self.items_table.repr_item_for_yaml(identifier, resolve=resolve)})
            else:
                unknowns.append(aYaml.YamlDumpWrap(value="UNKNOWN VARIABLE",
                                                   comment=identifier + " is not in variable list"))
        if defines:
            retVal.append(aYaml.YamlDumpDocWrap(defines, '!define', "Definitions",
                                                explicit_start=True, sort_mappings=True))
        if indexes:
            retVal.append(
                aYaml.YamlDumpDocWrap(indexes, '!index', "Installation index",
                                      explicit_start=True, sort_mappings=True))
        if unknowns:
            retVal.append(
                aYaml.YamlDumpDocWrap(unknowns, '!unknowns', "Installation index",
                                      explicit_start=True, sort_mappings=True))

        return retVal
